// /hooks/useSaveExamResults.ts
import { db } from '../firebase/config';
import { ExamSession } from '../types';

// Defines the type for the result object generated by the mock AI marker.
type MarkingResult = Omit<ExamSession, 'config' | 'questions' | 'answers'>;

/**
 * Saves a completed exam session to the mock Firestore database.
 * In this scaffolded version, it logs the data to the console.
 *
 * @param {string} userId - The ID of the user who completed the exam.
 * @param {MarkingResult} markingResult - The object containing feedback, scores, etc.
 * @param {Date} [date=new Date()] - The submission date.
 * @returns {Promise<string | undefined>} A promise that resolves with the mock document ID on success.
 */
export async function saveExamResults(userId: string, markingResult: MarkingResult, date = new Date()) {
  try {
    // Structure the data as it would be saved in a real Firestore document.
    const docData = {
      userId,
      ...markingResult,
      createdAt: date.toISOString(),
    };

    // Call the 'add' method on our mock db object.
    const result = await db.collection('examResults').add(docData);
    
    // Log success to the console for verification during testing.
    console.log('✅ Mock exam results saved successfully with ID:', result.id);
    return result.id;
  } catch (err) {
    // Log any errors that might occur in the mock process.
    console.error('❌ Mock save error:', err);
  }
}
